kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: moodledata-pvc
  namespace: moodle-probandouser33-qa
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
